#!/bin/sh
export GEMINI_API_KEY=$(grep "^GEMINI_API_KEY=" "$(cd "$(dirname "$0")/../.." && pwd)/.env" | cut -d'=' -f2)
export AUTODOC_MODE=both
"C:/Users/anup.shembade/AppData/Local/Programs/Python/Python313/python.exe" -m doc_generator.generator "$(cd "$(dirname "$0")/../.." && pwd)"